name: Update GitHub Stats
on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub stats
        run: |
          curl -L "https://github-readme-stats.vercel.app/api?username=margoar&show_icons=true" \
            -o gh-stats.svg

          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=margoar&layout=compact&langs_count=8" \
            -o gh-stats-language.svg

      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add gh-stats.svg gh-stats-language.svg

          git commit -m "chore: update GitHub stats" || exit 0

          git push
