name: Automated Stats

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create automated file
        run: |
          echo "Last automated update: $(date)" > automated-stats.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add automated-stats.txt
          git commit -m "chore: automated stats update" || exit 0
          git push
